### ISSUE TITLE
Correcting the license information published in Maven central for us.fatehi:schemacrawler to show EPL 1.0 like it does in the code

### ISSUE THREAD

**Issue by shantstepanian** [sualeh/SchemaCrawler#117]
Hi, I'd like to leverage schemacrawler for an Apache-licensed product, which means I'd want to use SchemaCrawler via the EPL 1.0 license (it is also licensed under GPL and LGPL)

I see that the Maven poms do link to EPL 1.0:
- https://github.com/sualeh/SchemaCrawler/blob/v14.14.04/pom.xml (parent pom has the license link)
- https://github.com/sualeh/SchemaCrawler/blob/v14.14.04/schemacrawler/pom.xml (child module does not override the value)

However, the pom that is in Maven central still only refers to LGPL. Although the Jar itself does contain a pom that has the EPL 1.0 license mentioned
- pom: https://repo1.maven.org/maven2/us/fatehi/schemacrawler/14.14.04/schemacrawler-14.14.04.pom
- jar: https://repo1.maven.org/maven2/us/fatehi/schemacrawler/14.14.04/schemacrawler-14.14.04.jar

Is it possible to correct the pom in Maven central for schemacrawler to mention EPL 1.0? (Assuming that this was your intention w/ that module). It seems like the code is correct, so this may happen in your release process, though I don't know the specifics of your release process

**Comment by sualeh** [comment]
[Shant](@shantstepanian), good to hear from you. I will fix this discrepancy. Are you referring to the [reladomo](https://github.com/goldmansachs/reladomo) project?

**Comment by shantstepanian** [comment]
Great, thanks!

No, not that project, but another one that will hopefully come soon into that same GitHub area

**Comment by sualeh** [comment]
[Shant](@shantstepanian), I have fixed the licensing in SchemaCrawler 14.05.01.

**Comment by shantstepanian** [comment]
Thanks. I see it fixed for schemacrawler,  db2, Oracle, and Sybase IQ

I still see hsqldb, postgresql, and sqlserver as GPL. The underlying drivers are BSD, BSD, and MIT license, respectively. Is it possible to change those as well? I'm not aware of the license compatibilities, though BSD and MIT are permissive

(We aren't yet using other distributions not named above, so I can't comment yet on whether the others are correct, but I can deal without the others for now)

**Comment by shantstepanian** [comment]
I've opened a new issue #118 as I see this issue was closed out
